name: livecom_ios
description: The iOS implementation of livecom
version: 1.1.2
homepage: https://github.com/LiveComSollutions/livecom-flutter/tree/main/livecom_ios
repository: https://github.com/LiveComSollutions/livecom-flutter/tree/main/livecom_ios

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  livecom_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        dartPluginClass: LiveComIOS
        pluginClass: LiveComIosPlugin
