name: livecom_plugin
description: Flutter plugin for LiveCom
version: 1.1.4
repository: https://github.com/LiveComSollutions/livecom-flutter/tree/main/livecom_plugin
homepage:

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  livecom_platform_interface: ^1.0.0
  livecom_android: ^1.0.0
  livecom_ios: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        default_package: livecom_ios
      android:
        default_package: livecom_android
