name: livecom_platform_interface
description: A common platform interface for the livecom plugin.
version: 1.0.0
homepage: https://github.com/LiveComSollutions/livecom-flutter/tree/main/livecom_platform_interface
repository: https://github.com/LiveComSollutions/livecom-flutter/tree/main/livecom_platform_interface
environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
